#!/bin/bash

BLACK="\033[0;37m"
GREEN="\033[1;32m"
RED="\033[0;31m"
NOCOLOR="\033[0m"

printf "${BLACK}========== 🟠 Run Commit 🟠 ===========\n${NOCOLOR}"

COMMIT_FILE=$1
COMMIT_MESSAGE=$(cat $1)

COMMIT_TYPES=(
  "🤖 Chore: Other changes"
  "📚 Docs: Documentation changes"
  "✨ Feat: New feature"
  "🐛 Fix: Bug fix"
  "⚡️ Perf: Performance improvement"
  "🔨 Refactor: Code refactoring"
  "🚨 Test: Adding tests"
)

exec < /dev/tty
PS3="Select Commit Type: "
while [ "$COMMIT_TYPE" = "" ]
do
  select COMMIT_TYPE in "${COMMIT_TYPES[@]}"
  do
    break
  done

  if [ "$COMMIT_TYPE" = "" ]
  then
    printf "${RED}Invalid Commit Type\n${NOCOLOR}"
  fi
done

echo $(echo $COMMIT_TYPE | sed "s| :|:|g" | sed "s|(.*)|$COMMIT_MESSAGE|g") > $COMMIT_FILE
printf "${GREEN}"
